
---

name: CI

on: [push, pull_request]

jobs:
  ui-lint-build-test:
    name: UI - Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install UI dependencies
        working-directory: ui
        run: npm ci

      - name: Lint UI
        working-directory: ui
        run: npm run lint

      - name: Build UI
        working-directory: ui
        run: npm run build

      - name: Test UI
        working-directory: ui
        run: npm test -- --coverage --watchAll=false

  backend-lint-build-test:
    name: Backend - Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check Rust formatting
        run: cargo fmt --check

      - name: Lint Rust code
        run: cargo clippy -- -D warnings

      - name: Build Rust backend
        run: cargo build --verbose

      - name: Run Rust tests
        run: cargo test --verbose

